[package]
name = "podmesh-integration-tests"
version = "0.1.0"
edition = "2024"
description = "Integration tests for podmesh"
publish = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["process"] }
podmesh-proxy = { workspace = true }
podmesh-sidecar = { workspace = true }
podmesh-agent = { workspace = true }
protocol = { workspace = true }
podmesh-scheduler = { workspace = true }
podctl = { workspace = true }
crypto = { workspace = true }
axum = { workspace = true }
axum-support = { workspace = true }
reqwest = { workspace = true }
env_logger = { workspace = true }
serial_test = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }

[features]
default = []
podman-tests = []
