[package]
name = "cli"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for podmesh"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
