[package]
name = "podmesh-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["env"] }
env_logger = { workspace = true }
log = { workspace = true }
protocol = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }

[dev-dependencies]
crypto = { workspace = true }
