[package]
name = "podmesh-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["env"] }
crypto = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
iroh = { workspace = true }
iroh-gossip = { workspace = true }
iroh-support = { workspace = true }
iroh-relay = { workspace = true }
log = { workspace = true }
protocol = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
tokio-util = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }
