[package]
name = "podmesh-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
libp2p = { workspace = true, features = ["relay", "autonat", "identify"] }
tokio = { workspace = true }
tracing_support = { path = "../shared/tracing_support" }
p2p = { workspace = true }
protocol = { workspace = true }
futures = { workspace = true }
axum = "0.8"
serde = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum-support = { workspace = true }
async-trait = "0.1"
thiserror = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }

