[package]
name = "podmesh-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
libp2p = { workspace = true, features = ["relay", "autonat", "identify"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7", features = ["compat"] }
log = { workspace = true }
env_logger = { workspace = true }
p2p = { workspace = true }
protocol = { workspace = true }
futures = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
axum-support = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
postcard = { workspace = true }
sha2 = { workspace = true }
crypto = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
serial_test = { workspace = true }

