[package]
name = "crypto"
version = "0.1.0"
edition = "2024"
description = "Crypto parts of podmesh"
license = "GPL-3.0-only"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand = { workspace = true }
base64 = { workspace = true }
dirs = { workspace = true }
ed25519-dalek = { workspace = true }
x25519-dalek = { workspace = true }
chacha20poly1305 = { workspace = true }
log = { workspace = true }
zeroize = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
