[package]
name = "p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
libp2p = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
protocol = { path = "../protocol" }
crypto = { path = "../crypto" }
base64 = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
