[package]
name = "podmesh-sidecar"
version = "0.1.0"
edition = "2024"

authors = ["Podmesh"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
crypto = { workspace = true }
iroh = { workspace = true }
iroh-support = { workspace = true }
rustls-pki-types = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
log = { workspace = true }
env_logger = { workspace = true }
protocol = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }

# Egress proxy dependencies
rustables = "0.8"
libc = "0.2"
socket2 = "0.5"
ipnetwork = "0.21"
tokio-util = { workspace = true }
postcard = { workspace = true }
sha2 = { workspace = true }

